### ISSUE TITLE
Use multi-alias

### ISSUE THREAD

**Issue by alanvardy** [SupaMic/SupaBattleSnake#2]
https://github.com/SupaMic/SupaBattleSnake/blob/21080a49929ac0a180a700478ec65f3e2eba2a0f/lib/supa_battle_snake.ex#L18

You can use the Multi-alias syntax, so instead of

```elixir
  alias SupaBattleSnake.GameBoard
  alias SupaBattleSnake.Snake
  alias SupaBattleSnake.MoveAgent
```

you can write

```elixir
  alias SupaBattleSnake.{GameBoard, MoveAgent, Snake}
```

**Comment by SupaMic** [comment]
This is much nicer except I can't figure out how to use the "as:" keyword in the Multi-alias syntax

`alias SupaBattleSnake.{[SnakeStruct, as: Snake], [GameBoardStruct, as: GameBoard]}`

might not be possible?

**Comment by alanvardy** [comment]
Unfortunately it isn't!
